### ISSUE TITLE
Ignore whole directories

### ISSUE THREAD

**Issue by rbarato** [tomusdrw/grunt-sync#33]
I have the following:

files: [{
          cwd: 'webapp',
          src: ['**','!/node_modules'],
          dest: /dist',
        }],

The node_modules directory is not being ignored, increasing the sync latency since it has to run the entire folder looking for changes. I've tried all configurations (**node_modules, **/node...) etc. Is this an issue or a misconception on my side?

Thanks!

**Comment by sandinjr** [comment]
Try this (added '/**' after directory name):

files: [{
cwd: 'webapp',
src: ['**','!/node_modules/**'],
dest: /dist',
}],

**Comment by rbarato** [comment]
Still looking into those :(

**Comment by tomusdrw** [comment]
Have you tried the solution provided by @sandinjr? It should look like this:
```
files: [{
cwd: 'webapp',
src: ['**','!/node_modules/**'],
dest: /dist',
}],
```

The plugin is using globbing patterns built in grunt so this should also help:
http://gruntjs.com/configuring-tasks#globbing-patterns

**Comment by sandinjr** [comment]
Thanks for writing it right, @tomusdrw. I didn't notice my stars got eaten by markdown :(
