### ISSUE TITLE
No "flatten" feature like in grunt-contrib-copy?

### ISSUE THREAD

**Issue by bunkscene** [tomusdrw/grunt-sync#35]
Hi,

Anyway you could implement a flatten feature like in grunt-contrib-copy?  This means that regardless of the source directory, the files are deployed to the specified destination without the source directory path.

Thanks,
Dave

**Comment by bunkscene** [comment]
I was able to use cwd do perform my desired action.  However, it still may be desirable to flatten the source if there are multiple directories in one call.

**Comment by tomusdrw** [comment]
I think it should work out of the box (though I didn't test that). The plugin is using grunt to configure files:
http://gruntjs.com/configuring-tasks#globbing-patterns
