### ISSUE TITLE
Crash if no files were modified

### ISSUE THREAD

**Issue by corvae** [tomusdrw/grunt-sync#38]
My sync task looks like this

    sync: {
        main: {
	    files: [{
	        cwd: '<%= pkg.destination %>',
		src: [ '**' ],
	        dest: '<%= deployDir %>',
	     }],
	     verbose: true, 
	     failOnError: true,
             compareUsing: "md5"
        }
    }

which works fine if there has been changes. The pkg.destination is a local directory, and deployDir is a network address.

If no files have been changed, the prompt will become unresponsive after listing all the files (ran with 'grunt syncTask -v'). I have to kill the node process manually.  

When I ran sync with 2 modified files (and 2 empty folders to create in dest), it took over 5 minues.

    Execution Time (2015-10-12 21:27:40 UTC)
    loading tasks      873ms  0%
    sync:main       5m 31.4s     ████████████████████████████████████ 100%
    Total 5m 32.3s

I guess most people use this with watch, so it's wouldn't really be as much of an issue.  But without using watch, is this actually a problem with grunt-sync, or perhaps an issue with copying over a slow network?

**Comment by corvae** [comment]
Well, I got my network issue worked out, and I think that was causing the node process to hang.  Sync seems to be working nicely. Thank you.

**Comment by tomusdrw** [comment]
Hi!
Great that you've managed to solve this. Indeed slow network connection can be a serious problem - especially in first phase when `glob` is trying to discover the whole file structure on remote destination.
