### ISSUE TITLE
Multiple src -> dest ?

### ISSUE THREAD

**Issue by davetgreen** [tomusdrw/grunt-sync#39]
hey @tomusdrw 

Is it possible to pass an array of src and dest paths to grunt-sync? I'd like a single task that uses config data from the gruntfile.js and then sync's each one.

**Comment by tomusdrw** [comment]
Hi!
`grunt-sync` is just using task configuration passed by Grunt. You can check if this works:
http://gruntjs.com/configuring-tasks#files-array-format

**Comment by davetgreen** [comment]
Of course! I'll give that a try, cheers!
