### ISSUE TITLE
Race condition in updateAndDelete causing ENOTEMPTY

### ISSUE THREAD

**Issue by jasonku** [tomusdrw/grunt-sync#41]
I am seeing a race condition where when using `updateAndDelete`, `grunt-sync` will attempt to remove a parent directory before it's finished removing a child directory or files. This results in the following error:

```
$ grunt sync
Running "sync:content" (sync) task
Fatal error: ENOTEMPTY: directory not empty, rmdir '...'
```

Looking at https://github.com/tomusdrw/grunt-sync/blob/master/tasks/sync.js#L261 , `promise.all` doesn't execute the array of promises in order or in series, so sorting `path.dirs` doesn't actually do anything. We either need to execute these sorted promises in series, or use something like [rimraf](https://github.com/isaacs/rimraf) to remove these directories.

**Comment by tomusdrw** [comment]
Great catch. I would go for synchronous delete (maybe even only if directory is not empty).
Using [rimraf] would break `ignoreInDest` option.

**Comment by jRichardeau** [comment]
I've got the same issue, Fatal error: ENOTEMPTY, rmdir "...", mostly when using UNC destination path.
