### ISSUE TITLE
npm-glob update

### ISSUE THREAD

**Issue by brianmontanaweb** [tomusdrw/grunt-sync#48]
An old version of glob that's referencing an old minimatch version, want me to do a PR for this?

`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Comment by tomusdrw** [comment]
Thanks for reporting. PR would be nice. I will have a look at it tomorrow.

**Comment by tomusdrw** [comment]
Fixed in 0.6.2

**Comment by brianmontanaweb** [comment]
Thanks Tom 👍

**Comment by tomusdrw** [comment]
Cheers! :)
