### ISSUE TITLE
update changelog or release logs?

### ISSUE THREAD

**Issue by rjrbt** [tomusdrw/grunt-sync#50]
npm is calling for `0.6.2` being the latest version of grunt-sync, but the change log and release versions on github stop in either `0.4.x` or `0.5.x`.

Can you push the latest version of your code that's in `npm` to github?

**Comment by tomusdrw** [comment]
The code in the repo is the latest one. In `0.6.0` major version of important dependencies were bumped (like `glob`), but I released `0.6.2` by accident (forgot to reset patch version when bumping minor).

I've updated readme changelog to represent latest version. Thanks for spotting that out and filing the issue!
