### ISSUE TITLE
when renaming files, it creates a new file

### ISSUE THREAD

**Issue by liron-navon** [tomusdrw/grunt-sync#55]
when I create a file and then need to rename it or move it to another folder, sync creates duplicates

how to reproduce:
a. create a file at src ie 'foo.txt'
b. run sync
c. rename the file in src ie 'bar.txt'

now there are both 'foo.txt' and 'bar.txt' in 'out' folder

here is my sync code:

            sync: {
                fonts: {
                    files: [{
                        cwd: "src",
                        src: ['**/*', '!**/*.ts'],
                        dest: "out",
                    }], // files
                    verbose: true,
                    failOnError: true,
                }
            },

**Comment by tomusdrw** [comment]
Have a look at `updateAndDelete` option.
