### ISSUE TITLE
Question about exclusion (!) syntax

### ISSUE THREAD

**Issue by sffc** [tomusdrw/grunt-sync#59]
I was trying to find where it is implemented in the code, but unless I'm missing something obvious I can't find it:

https://github.com/tomusdrw/grunt-sync/blob/master/tasks/sync.js

A few questions about it:

1. Where did the idea for using `!` originate (rather than some other syntax for doing exclusion patterns)?
2. Where is it implemented in grunt-sync?
3. Are you aware of any other projects using this syntax?

The reason I'm asking is because I'm working on an inclusion/exclusion engine for [ICU](http://site.icu-project.org/), and I was intrigued by the idea of using `!` for exclusion patterns and want to understand more of the history, particularly the degree to which this syntax is a convention.

**Comment by tomusdrw** [comment]
Hi @sffc, the pattern is blindly forwarded to https://github.com/isaacs/node-glob#glob-primer
The syntax is actually what they do support, so better direct the question to glob maintainers.

**Comment by sffc** [comment]
Got it, it's just from Glob directly.  Thanks for the pointer!
