### ISSUE TITLE
SyntaxError on node4

### ISSUE THREAD

**Issue by staabm** [tomusdrw/grunt-sync#61]
when running grunt-sync 0.8 on a node4 version, we run into a syntax error:

```
Loading "sync.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
>>   at exports.runInThisContext (vm.js:53:16)
>>   at Module._compile (module.js:374:25)
>>   at Object.Module._extensions..js (module.js:417:10)
>>   at Module.load (/deploy/kunzmann/ci/kunzmann/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:301:12)
>>   at Module.require (module.js:354:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> (/deploy/kunzmann/ci/kunzmann/node_modules/fs-extra/lib/index.js:6:3)
>>   at Module._compile (module.js:410:26)
>>   at Object.Module._extensions..js (module.js:417:10)
>>   at Module.load (/deploy/kunzmann/ci/kunzmann/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:301:12)
>>   at Module.require (module.js:354:17)
>>   at require (internal/module.js:12:17)
>>   at Object.<anonymous> (/deploy/kunzmann/ci/kunzmann/node_modules/grunt-sync/tasks/sync.js:1:72)
>>   at Module._compile (module.js:410:26)
>>   at Object.Module._extensions..js (module.js:417:10)
>>   at Module.load (/deploy/kunzmann/ci/kunzmann/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:301:12)
>>   at Module.require (module.js:354:17)
>>   at require (internal/module.js:12:17)
>>   at loadTask (/deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt/task.js:313:10)
>>   at /deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt/task.js:351:7
>>   at Array.forEach (native)
>>   at loadTasks (/deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt/task.js:350:11)
>>   at Task.task.loadNpmTasks (/deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt/task.js:398:5)
>>   at /deploy/kunzmann/ci/kunzmann/node_modules/load-grunt-tasks/index.js:34:10
>>   at Array.forEach (native)
>>   at module.exports (/deploy/kunzmann/ci/kunzmann/node_modules/load-grunt-tasks/index.js:26:29)
>>   at Object.module.exports (/deploy/kunzmann/ci/kunzmann/Gruntfile.js:257:32)
>>   at loadTask (/deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at Task.task.init (/deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt/task.js:434:5)
>>   at Object.grunt.tasks (/deploy/kunzmann/ci/kunzmann/node_modules/grunt/lib/grunt.js:111:8)
>>   at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:66:13)
>>   at Liftoff.execute (/usr/local/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:203:12)
>>   at module.exports (/usr/local/lib/node_modules/grunt-cli/node_modules/flagged-respawn/index.js:51:3)
>>   at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:195:5)
>>   at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:170:7)
>>   at nextTickCallbackWith0Args (node.js:419:9)
>>   at process._tickCallback (node.js:348:13)
```

since the package.json defines support for node4+ it would be great to fix the error

```
node -v
v4.2.6

npm -v
3.5.2

grunt --version
grunt-cli v1.3.2
grunt v1.0.4
```

**Comment by staabm** [comment]
ping @nwoltman since you worked on the latest version... do you have an idea what the problem is?

**Comment by bloep** [comment]
since v0.8 (#58) grunt-sync uses `fs-extra@6.0.1`, which relies on es6 rest parameters. They aren't supported in Node 4.

**Comment by tomusdrw** [comment]
I'd say we should drop support for old node versions, don't have resources though to test what's the minimal working version, so by lazy choice I'd say to set it to latest stable (or v10 if it works there)

**Comment by staabm** [comment]
> I'd say we should drop support for old node versions, don't have resources though to test what's the minimal working version, so by lazy choice I'd say to set it to latest stable (or v10 if it works there)

I am fine with this decision. we just need to make sure that the v0.8.0 version is not published on npm, so a node4 instance will get the 0.6.* releases which work on node4

**Comment by tomusdrw** [comment]
@staabm Indeed, I can probably yank `0.8.0` and publish `0.8.1` with higher requirements, do you think that would work?

**Comment by staabm** [comment]
thx for tagging and publishing 0.8.1.

I tried in a project which defines the following package.json
```
{
  "name": "theme",
  "version": "0.0.0",
  "description": "Template",
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "grunt": "^1.0.1",
    "grunt-contrib-clean": "^1.0.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-jshint": "^1.0.0",
    "grunt-contrib-less": "^1.4.0",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-postcss": "^0.8.0",
    "grunt-sync": "^0.6 || ^0.8",
    "load-grunt-tasks": "^3.5.2"
  }
}
```

but when running node4 on it, it picks 0.8.1 of grunt-sync... note sure why though

**Comment by staabm** [comment]
ok, after doing some research I see how this works
http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

it seems npm does not select the best fit of the given options, but just bails out on your not matching package constraints. Additionally you need to opt-in this behaviour with `npm config set engine-strict true`.

effectively npm seems not be able to pick the right package.

**Comment by nwoltman** [comment]
@staabm It seems like you should probably have this in your package.json:

```json
"grunt-sync": "0.7.0",
```

**Comment by staabm** [comment]
yeah this works, as long as I use node4. when using node10 this no longer works.

I expected npm to be smarter and use the information of the `engines` field while resolving the dependency tree. other package manager (e.g. composer in php) can do this pretty well.

**Comment by tomusdrw** [comment]
@staabm thanks for heads up, I wasn't aware that it's not capable of figuring out the right version either. In fact since `fs-extra` has `engines` specified, I'd expect that transitively the warning should be already generated, since we depend on it. Basically the `engines` of the package should be the strictest `engines` of every dependency in the tree, but it seems that this field is literally useless.

**Comment by staabm** [comment]
I kind of agree. still its good we have it documented. thx for your fast feedback.
