### ISSUE TITLE
Deprecation notice and alternative

### ISSUE THREAD

**Issue by JamesSkemp** [tomusdrw/grunt-sync#63]
I'm looking at an inherited application that is using grunt-sync as part of the build process.

Digging into things, I noticed the deprecation notice in the README.

1. Is there a recommended alternative, or is this package abandoned instead of deprecated?
2. May I recommend updating the description on GitHub to note that it's deprecated (or abandoned)? (I personally use the `[DEPRECATED] ` prefix as I've seen it used on a number of other projects.)

Thanks!

**Comment by tomusdrw** [comment]
Hi @JamesSkemp 

1. I don't know of alternatives, didn't need one myself. Happy to update the readme (or accept a PR) if you find and recommend one. It's not being actively developed, but I'm still around - happy to handover to someone who is interested in a more active maintenance.
2. Sure, changed.

**Comment by lonix1** [comment]
@JamesSkemp In same boat as you... Did you find an alternative?

**Comment by JamesSkemp** [comment]
@lonix1 I did not. I actually haven't been able to dig back into that project, so I haven't looked in at least the last 11 months.

(For my future reference, dsg.)

**Comment by lonix1** [comment]
dsg? Direct Shift Gearbox? :smile: 

There's this native [alternative](https://github.com/gruntjs/grunt-contrib-copy/issues/165#issuecomment-222095366), but it's messy

And there's the [grunt-newer](https://www.npmjs.com/package/grunt-newer) plugin which works nicely in many cases

**Comment by JamesSkemp** [comment]
Well, two of the words have the same number of letters as the correct words. :D

dsg = Digital Style Guide

This isn't ours, but one of the many that the team took inspiration from: https://designsystem.digital.gov/

Unfortunately the team that was working on the DSG completely turned over, and I'm afraid of the answer I'll get if I poke it to make some technical improvements (since it's not perfect, but still extremely helpful), so ... the project lies dormant. :|

**Comment by lonix1** [comment]
Wow that's a really stylish dsg! (See I can speak the lingo).

FYI I've been using grunt-newer for a day or so, and it's great. A perfect replacement for this plugin, and it works with all other plugins too. You'd use it in tandem with grunt-contrib-copy.

**Comment by lonix1** [comment]
Actually, @tomusdrw that might be a good idea to recomment to anyone who asks this question again.

i.e. use `grunt-newer` + `grunt-contrib-copy`.

**Comment by tomusdrw** [comment]
@lonix1 thanks for the recommendation. I've updated the README.md.
